import { afterAll, beforeAll, describe, expect, test } from "bun:test";
import { existsSync } from "node:fs";
import { readFile, rm, writeFile } from "node:fs/promises";

// Use a non-default port so the test never collides with the user's own
// `bun run dev` (which binds 4321).
const PORT = 4399;
const BASE = `http://127.0.0.1:${PORT}`;
const READY_TIMEOUT_MS = 120_000;

const scaffoldDir = new URL("..", import.meta.url).pathname;
const workerDir = `${scaffoldDir}worker`;
const indexPath = `${workerDir}/index.js`;
const heyPath = `${workerDir}/hey.js`;

const HEY_HANDLER = `// Test-only handler injected by test/dev-smoke.test.ts. Removed afterwards.
export async function handleHey() {
  return new Response('Hello!', {
    status: 200,
    headers: { 'Content-Type': 'text/plain' },
  });
}
`;

const INDEX_WITH_HEY = `// Test-only worker entry generated by test/dev-smoke.test.ts.
import { handleHey } from './hey.js';

const ROUTES = {
  '/~/hey': { handler: handleHey, description: 'Hello World' },
};

export default {
  async fetch(request, env, ctx) {
    const pathname = new URL(request.url).pathname;
    const route = Object.entries(ROUTES).find(([prefix]) => pathname.startsWith(prefix));
    if (route) {
      const [, { handler, description }] = route;
      try {
        return await handler(request, ctx);
      } catch (error) {
        console.error(\`Error in \${description}:\`, error);
        return new Response('Internal Server Error', { status: 500 });
      }
    }
    return new Response('Not Found', { status: 404 });
  }
};
`;

let dev: ReturnType<typeof Bun.spawn> | null = null;
let originalIndex: string | null = null;

async function runBuild() {
  const build = Bun.spawn(["bun", "run", "build"], {
    cwd: scaffoldDir,
    stdout: "inherit",
    stderr: "inherit",
    env: { ...process.env, CI: "1", NODE_ENV: "production" },
  });
  const exitCode = await build.exited;
  if (exitCode !== 0) {
    throw new Error(`build failed with exit code ${exitCode}`);
  }
}

async function waitForReady(timeoutMs: number) {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    try {
      const r = await fetch(BASE + "/", { signal: AbortSignal.timeout(3_000) });
      if (r.status === 200) return;
    } catch {}
    await Bun.sleep(750);
  }
  throw new Error(`dev server not ready on ${BASE} within ${timeoutMs}ms`);
}

async function teardown() {
  dev?.kill();
  if (originalIndex !== null) {
    await writeFile(indexPath, originalIndex);
    originalIndex = null;
  }
  if (existsSync(heyPath)) {
    await rm(heyPath);
  }
}

beforeAll(async () => {
  // The shipped scaffold has no active /~/* routes. Inject a `/~/hey` route
  // for the duration of the test by writing a temporary worker/hey.js and
  // overwriting worker/index.js to wire it up; teardown restores both.
  originalIndex = await readFile(indexPath, "utf8");
  await writeFile(heyPath, HEY_HANDLER);
  await writeFile(indexPath, INDEX_WITH_HEY);

  await runBuild();

  dev = Bun.spawn(
    ["bun", "run", "preview", "--", "--port", String(PORT), "--host", "127.0.0.1"],
    {
      cwd: scaffoldDir,
      stdout: "inherit",
      stderr: "inherit",
      env: { ...process.env, BROWSER: "none", CI: "1", NODE_ENV: "production" },
    },
  );

  try {
    await waitForReady(READY_TIMEOUT_MS);
  } catch (e) {
    await teardown();
    throw e;
  }
}, READY_TIMEOUT_MS + 10_000);

afterAll(teardown);

// Astro is configured with `trailingSlash: "always"`, so all non-root paths
// must end in `/` — without the slash Astro's dev server intercepts with a
// "did you mean .../?" 404 page.

describe("scaffold preview server (bun run preview) smoke", () => {
  test("/~/hey/ is served by the injected worker handler", async () => {
    const r = await fetch(BASE + "/~/hey/");
    expect(r.status).toBe(200);
    expect(r.headers.get("content-type") ?? "").toContain("text/plain");
    expect((await r.text()).trim()).toBe("Hello!");
  });

  test("homepage renders as static HTML", async () => {
    const r = await fetch(BASE + "/");
    expect(r.status).toBe(200);
    expect(r.headers.get("content-type") ?? "").toContain("text/html");
  });

  test("unknown path returns a 404", async () => {
    // In production wrangler's run_worker_first restricts the worker to /~/*
    // and not_found_handling = "404-page" serves the prerendered 404.astro
    // (text/html). In dev the worker entry currently sees every unmatched
    // path, so this just asserts the status — not which layer rendered it.
    const r = await fetch(BASE + "/no-such-page-xyz/");
    expect(r.status).toBe(404);
  });

  test("/404/ renders the prerendered 404.astro page", async () => {
    const r = await fetch(BASE + "/404/");
    expect(r.headers.get("content-type") ?? "").toContain("text/html");
    const body = await r.text();
    expect(body).toContain("404");
    expect(body).toContain("Page not found");
  });
});
